### ISSUE TITLE
Toggling Dark/Light Mode

### ISSUE THREAD

**Issue by shaneapen** [yanchokraev/grayshift#1]
Toggling dark/light mode with[ Darkmode.js](https://darkmodejs.learn.uno/) doesn't seem to work properly. Any ideas on why that happens?

**Comment by yanchokraev** [comment]
I don't see any reason why it shouldn't work. Do you have a demo?

**Comment by shaneapen** [comment]
The toggle button somehow changes the background color and it's not working as expected.
<img width="1552" alt="Screenshot 2020-02-29 at 5 40 59 PM" src="https://user-images.githubusercontent.com/8535661/75607216-b60ffd80-5b1a-11ea-878f-7d025a51e02e.png">

I couldn't find any methods to manually toggle the `prefers-color-scheme` property. What would you suggest if I wanted to add a Dark/Light mode switcher to the GSKit made webpage?

**Comment by yanchokraev** [comment]
From what I can see darkmode.js it's not meant for that purpose. darkmode.js creates its own color scheme.

I actually haven't tried before to manually trigger `prefers-color-scheme` on grayshift.
