### ISSUE TITLE
Sidebar component

### ISSUE THREAD

**Issue by tiagocassio** [yanchokraev/grayshift#3]
Hello!

First, i want to say THANK YOU for this great work! The simplicity puted in this kit makes me adopt your work on my new personal project.

Second, i have a question: Does this kit have a sidebar component or something similar? 

Cheers.

**Comment by yanchokraev** [comment]
Hi,

I'm glad you liked it.

I'm currently preparing the docs of Grayshift and I'm using a similar sidebar to this one:

```
<ul class="nav nav-tabs flex-column" style="padding: .75rem;">
  <li class="nav-item">
    <a class="nav-link active" href="#" style="padding: .75rem;">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#" style="padding: .75rem;">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#" style="padding: .75rem;">Link</a>
  </li>
</ul>
```

<img width="1436" alt="sidebar" src="https://user-images.githubusercontent.com/54913325/87930464-cce6ca80-ca90-11ea-89cd-cc8403b5baa7.png">

You can wrap it inside a grid layout.

```
<div class="row">
  <div class="col-md-4">
    <!-- Sidebar -->
  </div>
  <div class="col-md-8">
    <!-- Content -->
  </div>
</div>
```
