### ISSUE TITLE
More Bootstrap components

### ISSUE THREAD

**Issue by rd18aac** [yanchokraev/grayshift#4]
Love this theme overlay!

Would be cool to see more core Bootstrap components included in the documentation like badges, alerts, carousels and pagination.

**Comment by yanchokraev** [comment]
You can make badges and alerts with utilities. We even use badges in some of our examples. We used to have pagination, breadcrumb, tooltips, and tables. Now we don't, but we can consider bringing them back optionally. Most frameworks do too much, so we try to keep it clean and tidy.
