### ISSUE TITLE
Make library available via cdn

### ISSUE THREAD

**Issue by khabubu** [yanchokraev/grayshift#5]
I love this library. I use it for most of the web projects I create. I was wondering if you would consider making this library available via cdn.

Thanks

**Comment by yanchokraev** [comment]
Have you tried the jsDelivr CDN?

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yanchokraev/grayshift@1.0.0/css/grayshift.min.css" integrity="sha384-GJupCSwpa/5Jlkr/zMNCiBxPP7//lA3VTn0C5aOao0nhGEskGTL19lBzk0eVmfUC" crossorigin="anonymous">`

**Comment by khabubu** [comment]
No, it wasn't apparent on the Readme file for getting started. Can I make a pull request for this?

**Comment by yanchokraev** [comment]
Yes, go ahead.

https://grayshift.io/docs/getting-started/introduction/

You might find this useful.
