### ISSUE TITLE
Feature Request : Carousel

### ISSUE THREAD

**Issue by N1NG4** [yanchokraev/grayshift#6]
This is the Best component library in my choice. I like the speed and size of this library just one thing is missing that is carousel. After this everything is very good. So I request that you should add a carousel component.

**Comment by yanchokraev** [comment]
I'm not quite sure if we ever gonna add a carousel. It's so 2010, image carousels, sliders, etc. I don't remember the last time I needed one tbh. Dragging and flicking it's a different story but perhaps you'll need a third-party library to achieve that.

**Comment by N1NG4** [comment]
All Libraries are not lite so I've requested here but no results 😔. I'll use any other library for Carousel. Also thanks for your this Library

**Comment by N1NG4** [comment]
Can you please Share any liteweight solution for Carousel?

**Comment by yanchokraev** [comment]
Is there something specific that you are trying to achieve? What features do you need?
